# POST https://localhost:7064/students HTTP/1.1
# content-type : application/json" 

# {
#     "firstName": "Jencir", "lastName" : "Siraj", "email" : "jencir@email.com"
# }

GET https://localhost:7064/students