# POST https://localhost:7064/courses HTTP/1.1
# content-type : application/json" 

# {
#     "name": "FIN FS13", "startDate" : "2023-02-26", "status" : "OnGoing", "size" : 15
# }

# GET https://localhost:7064/courses?status=NotStarted

# POST https://localhost:7064/students HTTP/1.1
# content-type : application/json" 

# {
#     "FirstName": "Ishal", "LastName" : "Anas", "Email" : "ishal@gmail.com"
# }

# PUT https://localhost:7064/courses/1 HTTP/1.1
# content-type : application/json" 

# {
#     "name": "FIN FS20", "startDate" : "2023-04-26", "status" : "NotStarted", "size" : 15
# }

# DELETE https://localhost:7064/students/1